# Generated by Django 6.0.2 on 2026-03-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_distance_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='distance',
            name='length',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
